# stage 1: build the tunnel binary
FROM golang:1.25.3-alpine3.22 AS builder

WORKDIR /app
# create /app directory and then cd into it


# copy into /app
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . . 
# copy everything in current directory into /app

RUN go build -v -o /out/tunnel ./cmd/tunnel
# build the tunnel binary and name it tunnel

# stage 2: run
FROM alpine:3.22
WORKDIR /app
COPY --from=builder /out/tunnel /app/tunnel

ENTRYPOINT ["./tunnel"]